usage: conda [-h] [--no-plugins] [-V] COMMAND ...
conda: error: argument COMMAND: invalid choice: 'deactivate' (choose from 'clean', 'compare', 'config', 'create', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'build', 'content-trust', 'convert', 'debug', 'develop', 'doctor', 'index', 'inspect', 'metapackage', 'render', 'skeleton', 'pack', 'server', 'token', 'repo', 'env', 'verify')
usage: conda [-h] [--no-plugins] [-V] COMMAND ...
conda: error: argument COMMAND: invalid choice: 'deactivate' (choose from 'clean', 'compare', 'config', 'create', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'build', 'content-trust', 'convert', 'debug', 'develop', 'doctor', 'index', 'inspect', 'metapackage', 'render', 'skeleton', 'repo', 'pack', 'token', 'env', 'server', 'verify')
no change     /curc/sw/anaconda3/2023.09/condabin/conda
no change     /curc/sw/anaconda3/2023.09/bin/conda
no change     /curc/sw/anaconda3/2023.09/bin/conda-env
no change     /curc/sw/anaconda3/2023.09/bin/activate
no change     /curc/sw/anaconda3/2023.09/bin/deactivate
no change     /curc/sw/anaconda3/2023.09/etc/profile.d/conda.sh
no change     /curc/sw/anaconda3/2023.09/etc/fish/conf.d/conda.fish
no change     /curc/sw/anaconda3/2023.09/shell/condabin/Conda.psm1
no change     /curc/sw/anaconda3/2023.09/shell/condabin/conda-hook.ps1
no change     /curc/sw/anaconda3/2023.09/lib/python3.11/site-packages/xontrib/conda.xsh
no change     /curc/sw/anaconda3/2023.09/etc/profile.d/conda.csh
no change     /home/mlippincott@xsede.org/.bashrc
No action taken.
Processing well_fov C11-2 for patient NF0018
Processing directory  of Segmenting Nuclei
  0%|          | 0/12 [00:00<?, ?it/s]  8%|▊         | 1/12 [00:02<00:25,  2.34s/it] 17%|█▋        | 2/12 [00:02<00:12,  1.23s/it] 25%|██▌       | 3/12 [00:03<00:07,  1.16it/s] 33%|███▎      | 4/12 [00:03<00:05,  1.44it/s] 42%|████▏     | 5/12 [00:04<00:04,  1.68it/s] 50%|█████     | 6/12 [00:04<00:03,  1.85it/s] 58%|█████▊    | 7/12 [00:04<00:02,  1.95it/s] 67%|██████▋   | 8/12 [00:05<00:01,  2.04it/s] 75%|███████▌  | 9/12 [00:05<00:01,  2.11it/s] 83%|████████▎ | 10/12 [00:06<00:00,  2.19it/s] 92%|█████████▏| 11/12 [00:06<00:00,  2.24it/s]100%|██████████| 12/12 [00:07<00:00,  2.29it/s]100%|██████████| 12/12 [00:07<00:00,  1.69it/s]
Completed Nuclei Segmentation
Segmenting Cells
Completed Cell Segmentation
Segmenting Organoids
  0%|          | 0/25 [00:00<?, ?it/s]  8%|▊         | 2/25 [00:00<00:01, 15.51it/s] 16%|█▌        | 4/25 [00:00<00:01, 13.91it/s] 24%|██▍       | 6/25 [00:00<00:01, 14.86it/s] 32%|███▏      | 8/25 [00:00<00:01, 14.07it/s] 40%|████      | 10/25 [00:00<00:01, 13.68it/s] 48%|████▊     | 12/25 [00:00<00:00, 14.43it/s] 56%|█████▌    | 14/25 [00:00<00:00, 13.89it/s] 64%|██████▍   | 16/25 [00:01<00:00, 14.46it/s] 72%|███████▏  | 18/25 [00:01<00:00, 13.89it/s] 80%|████████  | 20/25 [00:01<00:00, 13.55it/s] 88%|████████▊ | 22/25 [00:01<00:00, 14.21it/s] 96%|█████████▌| 24/25 [00:01<00:00, 13.73it/s]100%|██████████| 25/25 [00:01<00:00, 13.95it/s]
  0%|          | 0/10 [00:00<?, ?it/s] 10%|█         | 1/10 [00:02<00:22,  2.48s/it] 20%|██        | 2/10 [00:03<00:11,  1.45s/it] 30%|███       | 3/10 [00:03<00:07,  1.14s/it] 40%|████      | 4/10 [00:04<00:06,  1.04s/it] 50%|█████     | 5/10 [00:05<00:05,  1.01s/it] 60%|██████    | 6/10 [00:06<00:04,  1.04s/it] 70%|███████   | 7/10 [00:07<00:03,  1.03s/it] 80%|████████  | 8/10 [00:08<00:02,  1.03s/it] 90%|█████████ | 9/10 [00:10<00:01,  1.04s/it]100%|██████████| 10/10 [00:11<00:00,  1.03s/it]100%|██████████| 10/10 [00:11<00:00,  1.10s/it]
Completed Organoid Segmentation
Decoupling nuclei
0it [00:00, ?it/s]2it [00:00, 11.30it/s]4it [00:00, 13.15it/s]6it [00:00, 14.75it/s]8it [00:00, 15.47it/s]10it [00:00, 16.07it/s]12it [00:00, 14.90it/s]13it [00:00, 15.24it/s]
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'label'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/2.segment_images/scripts/4.reconstruct_3D_masks.py", line 372, in <module>
    mask[mask == tmp_df.iloc[i]["original_label"]] = tmp_df.iloc[i]["label"]
                                                     ~~~~~~~~~~~~~~^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'label'
Decoupling cell
0it [00:00, ?it/s]1it [00:00,  9.93it/s]3it [00:00,  8.61it/s]4it [00:00,  7.77it/s]5it [00:00,  7.39it/s]6it [00:00,  7.18it/s]7it [00:00,  7.06it/s]8it [00:01,  7.36it/s]9it [00:01,  7.68it/s]10it [00:01,  7.93it/s]11it [00:01,  7.54it/s]13it [00:01,  9.56it/s]13it [00:01,  8.18it/s]
Decoupling organoid
0it [00:00, ?it/s]3it [00:00, 17.22it/s]5it [00:00, 11.17it/s]7it [00:00,  9.66it/s]9it [00:00,  9.06it/s]10it [00:01,  8.85it/s]12it [00:01, 10.20it/s]13it [00:01, 10.77it/s]
Traceback (most recent call last):
  File "/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/2.segment_images/scripts/4.reconstruct_3D_masks.py", line 275, in <module>
    df["indexes"] = df["index1"].astype(str) + "-" + df["index2"].astype(str)
                    ~~^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'index1'
Traceback (most recent call last):
  File "/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/2.segment_images/scripts/5.create_cytoplasm_masks.py", line 74, in <module>
    ).resolve(strict=True)
      ^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/pathlib.py", line 993, in resolve
    s = os.path.realpath(self, strict=strict)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 416, in realpath
  File "<frozen posixpath>", line 451, in _joinrealpath
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/data/NF0018/processed_data/C11-2/nuclei_masks_reconstructed.tiff'
Segmentation complete
