usage: conda [-h] [--no-plugins] [-V] COMMAND ...
conda: error: argument COMMAND: invalid choice: 'deactivate' (choose from 'clean', 'compare', 'config', 'create', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'build', 'content-trust', 'convert', 'debug', 'develop', 'doctor', 'index', 'inspect', 'metapackage', 'render', 'skeleton', 'env', 'server', 'repo', 'token', 'verify', 'pack')
usage: conda [-h] [--no-plugins] [-V] COMMAND ...
conda: error: argument COMMAND: invalid choice: 'deactivate' (choose from 'clean', 'compare', 'config', 'create', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'build', 'content-trust', 'convert', 'debug', 'develop', 'doctor', 'index', 'inspect', 'metapackage', 'render', 'skeleton', 'server', 'env', 'repo', 'verify', 'pack', 'token')
no change     /curc/sw/anaconda3/2023.09/condabin/conda
no change     /curc/sw/anaconda3/2023.09/bin/conda
no change     /curc/sw/anaconda3/2023.09/bin/conda-env
no change     /curc/sw/anaconda3/2023.09/bin/activate
no change     /curc/sw/anaconda3/2023.09/bin/deactivate
no change     /curc/sw/anaconda3/2023.09/etc/profile.d/conda.sh
no change     /curc/sw/anaconda3/2023.09/etc/fish/conf.d/conda.fish
no change     /curc/sw/anaconda3/2023.09/shell/condabin/Conda.psm1
no change     /curc/sw/anaconda3/2023.09/shell/condabin/conda-hook.ps1
no change     /curc/sw/anaconda3/2023.09/lib/python3.11/site-packages/xontrib/conda.xsh
no change     /curc/sw/anaconda3/2023.09/etc/profile.d/conda.csh
no change     /home/mlippincott@xsede.org/.bashrc
No action taken.
Processing well_fov E6-3 for patient NF0018
Processing directory  of Segmenting Nuclei
  0%|          | 0/12 [00:00<?, ?it/s]  8%|▊         | 1/12 [00:01<00:20,  1.87s/it] 17%|█▋        | 2/12 [00:02<00:11,  1.11s/it] 25%|██▌       | 3/12 [00:03<00:07,  1.14it/s] 33%|███▎      | 4/12 [00:03<00:06,  1.32it/s] 42%|████▏     | 5/12 [00:04<00:04,  1.44it/s] 50%|█████     | 6/12 [00:04<00:03,  1.53it/s] 58%|█████▊    | 7/12 [00:05<00:03,  1.58it/s] 67%|██████▋   | 8/12 [00:05<00:02,  1.63it/s] 75%|███████▌  | 9/12 [00:06<00:01,  1.68it/s] 83%|████████▎ | 10/12 [00:07<00:01,  1.71it/s] 92%|█████████▏| 11/12 [00:07<00:00,  1.77it/s]100%|██████████| 12/12 [00:08<00:00,  1.83it/s]100%|██████████| 12/12 [00:08<00:00,  1.48it/s]
Traceback (most recent call last):
  File "/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/2.segment_images/scripts/0.segment_nuclei_organoids.py", line 185, in <module>
    np.save(mask_path / "nuclei_reconstruction_dict.npy", reconstruction_dict)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/numpy/lib/npyio.py", line 542, in save
    file_ctx = open(file, "wb")
               ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/data/NF0018/processed_data/E6-3/nuclei_reconstruction_dict.npy'
Completed Nuclei Segmentation
Segmenting Cells
Completed Cell Segmentation
Segmenting Organoids
  0%|          | 0/25 [00:00<?, ?it/s]  8%|▊         | 2/25 [00:00<00:02, 10.94it/s] 16%|█▌        | 4/25 [00:00<00:02,  9.98it/s] 24%|██▍       | 6/25 [00:00<00:01, 10.56it/s] 32%|███▏      | 8/25 [00:00<00:01, 10.06it/s] 40%|████      | 10/25 [00:00<00:01,  9.82it/s] 48%|████▊     | 12/25 [00:01<00:01, 10.29it/s] 56%|█████▌    | 14/25 [00:01<00:01,  9.96it/s] 64%|██████▍   | 16/25 [00:01<00:00, 10.36it/s] 72%|███████▏  | 18/25 [00:01<00:00,  9.97it/s] 80%|████████  | 20/25 [00:01<00:00,  9.72it/s] 88%|████████▊ | 22/25 [00:02<00:00, 10.12it/s] 96%|█████████▌| 24/25 [00:02<00:00,  9.82it/s]100%|██████████| 25/25 [00:02<00:00,  9.70it/s]100%|██████████| 25/25 [00:02<00:00,  9.98it/s]
  0%|          | 0/10 [00:00<?, ?it/s] 10%|█         | 1/10 [00:03<00:34,  3.84s/it] 20%|██        | 2/10 [00:05<00:21,  2.66s/it] 30%|███       | 3/10 [00:07<00:15,  2.25s/it] 40%|████      | 4/10 [00:09<00:12,  2.04s/it] 50%|█████     | 5/10 [00:10<00:09,  1.91s/it] 60%|██████    | 6/10 [00:12<00:07,  1.82s/it] 70%|███████   | 7/10 [00:14<00:05,  1.76s/it] 80%|████████  | 8/10 [00:15<00:03,  1.71s/it] 90%|█████████ | 9/10 [00:17<00:01,  1.66s/it]100%|██████████| 10/10 [00:18<00:00,  1.60s/it]100%|██████████| 10/10 [00:18<00:00,  1.87s/it]
Completed Organoid Segmentation
Decoupling nuclei
Traceback (most recent call last):
  File "/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/2.segment_images/scripts/3.segmentation_decoupling.py", line 110, in <module>
    ).resolve(strict=True)
      ^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/pathlib.py", line 993, in resolve
    s = os.path.realpath(self, strict=strict)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 416, in realpath
  File "<frozen posixpath>", line 451, in _joinrealpath
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/data/NF0018/processed_data/E6-3/nuclei_reconstruction_dict.npy'
Traceback (most recent call last):
  File "/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/2.segment_images/scripts/4.reconstruct_3D_masks.py", line 100, in <module>
    input_image_dir = pathlib.Path(mask_dir / "nuclei_masks_decoupled.tiff").resolve(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/pathlib.py", line 993, in resolve
    s = os.path.realpath(self, strict=strict)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 416, in realpath
  File "<frozen posixpath>", line 451, in _joinrealpath
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/data/NF0018/processed_data/E6-3/nuclei_masks_decoupled.tiff'
Decoupling cell
0it [00:00, ?it/s]1it [00:00,  7.75it/s]2it [00:00,  6.38it/s]3it [00:00,  4.75it/s]4it [00:00,  4.25it/s]5it [00:01,  4.02it/s]6it [00:01,  3.91it/s]7it [00:01,  4.04it/s]8it [00:01,  4.12it/s]9it [00:02,  3.97it/s]10it [00:02,  3.87it/s]11it [00:02,  3.79it/s]12it [00:02,  4.20it/s]13it [00:02,  4.41it/s]
Decoupling organoid
0it [00:00, ?it/s]1it [00:00,  8.93it/s]2it [00:00,  9.30it/s]3it [00:00,  7.50it/s]4it [00:00,  6.01it/s]5it [00:00,  5.40it/s]6it [00:01,  5.07it/s]7it [00:01,  4.92it/s]8it [00:01,  4.84it/s]9it [00:01,  4.08it/s]10it [00:02,  3.73it/s]11it [00:02,  3.89it/s]12it [00:02,  4.46it/s]13it [00:02,  5.11it/s]
Traceback (most recent call last):
  File "/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/2.segment_images/scripts/5.create_cytoplasm_masks.py", line 74, in <module>
    ).resolve(strict=True)
      ^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/pathlib.py", line 993, in resolve
    s = os.path.realpath(self, strict=strict)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 416, in realpath
  File "<frozen posixpath>", line 451, in _joinrealpath
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/data/NF0018/processed_data/E6-3/nuclei_masks_reconstructed.tiff'
Segmentation complete
